Page404
Daniil-Khlyvniuk/final-project pull request #16
Opened 2021-10-31 16:11 UTC by nikolasdelunko

all good!

2021-10-31 19:17 UTC, Vitaliy-1809 commented on client/src/pages/Page404/Page404.js
> +const theme = createTheme({
Нужно внести коррективы: 

У нас есть уже созданная Тема в: utils/Theme.js
Добавь там необходимое свойство и подтяни оттуда

2021-10-31 19:18 UTC, Vitaliy-1809 commented on client/src/pages/Page404/Page404.scss
> +.errorPage{
И по стилям
Мы договаривались, что не используем SCSS
Нужно прописать стили, как в MUI (styled или makeStyles)

2021-10-31 19:19 UTC, Vitaliy-1809 reviewed
Есть комментарии в двух местах. Внеси, пожалуйста

2021-10-31 19:20 UTC, AlexMaybee requested changes
Ждем правки

2021-10-31 19:35 UTC, AlexMaybee commented on client/src/pages/Page404/Page404.js
> +const theme = createTheme({
Надо почистить package.json от неиспользуемых модулей.
Ярик, удали node-sass на своей стороне перед push.

2021-11-01 08:55 UTC, nikolasdelunko commented
Готово поправил

2021-11-01 09:04 UTC, closed without merging